### ISSUE TITLE
Selecting text in documentation popup makes text unreadable 

### ISSUE THREAD

**Issue by suhaybu** [xqsit94/zed-xqsit-theme#2]
When selecting text in the documentation popups, the opacity of the highlight does not allow for the text to be readable for some reason.

Attached a video to showcase the issue

https://github.com/user-attachments/assets/cfaac178-03c0-438f-a3b7-9fe43bf7f8c3

**Comment by xqsit94** [comment]
Thanks @Suhaybu let me know your opinion this PR #3

**Comment by suhaybu** [comment]
> Thanks @Suhaybu let me know your opinion this PR #3

Looks good to me! Tried it with "experimental.theme_overrides". Thank you very much!
